### ISSUE TITLE
About how to get the POSE data

### ISSUE THREAD

**Issue by Scoeur1** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#1]
Could you please tell me which  human pose estimation model is used to get the pose. pkl file of this project? Whether to pass the BBox data into the Model？

**Comment by OSU-Haolin** [comment]
Thanks for your interest in our project!
For your question, the human poses are generated by the **OpenPose** model (refer to https://github.com/CMU-Perceptual-Computing-Lab/openpose)

**Comment by Scoeur1** [comment]
Thank you for your reply.
I have a great interest in this area. I was wondering if it could be successfully reproduced using the environment and code you presented.
Can you tell me some specific versions of some environment configurations? Thank you so much if you can. My email is bjkjdxsff.163.com.
