### ISSUE TITLE
Results are different compared with the benchmark paper

### ISSUE THREAD

**Issue by xingchenzhang** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#2]
Hi,

Thank you very much for your nice work!

I am just wondering why the results of SingleRNN, SF-GRU and PCPA are different from what are reported in the benchmark paper "Benchmarking for Evaluating Pedestrian Action Preciction"?

It seems that you are using the same dataset and configuration with the paper. Maybe you have some specific processing steps?

Many thanks!
Xingchen

**Comment by OSU-Haolin** [comment]
Thanks for your interest in our work!

Based on the original code from the benchmark, we cannot reproduce the same results in their paper. We asked that but got no response.
Experiments in our work were conducted by the code here, and experimental configurations were kept the same. To convince it, later we will release the pretrained models for reproducing the results in our paper.

**Comment by xingchenzhang** [comment]
Thanks!

**Comment by OSU-Haolin** [comment]
> Thanks!

Now pre-trained models were uploaded and you can see links in README.
It is better to try a larger dataset such as the PIE dataset for achieving more reliable results.
