### ISSUE TITLE
GRU modules have dimension error 

### ISSUE THREAD

**Issue by Jennifercheukyin** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#3]
Hi! 
I ran the 'MASK_PCPA_jaad_2d.yaml" config file but got this dimension error:
ValueError: Input 0 of layer enc0_local_context_cnn is incompatible with the layer: expected ndim=3, found ndim=5. Full shape received: (None, 16, 224, 224, 3)
I don't think the tensor of this size can be passed in GRU. The tensor from mask_cnn seems to better fit the GRU input size. Do you mind elaborate a bit how tensors flow from CNN to GRU in this special case? 
Thank you!

**Comment by OSU-Haolin** [comment]
Hi! Jennifer,
In the shape of (16,224,224,3), 16 means the size of time frames (16 frames of mask images generated by every single mask-cnn) and (224,224,3) is the size of a single mask image. The size of (16,224,224,3) is fitted for RNN (gru).
I cannot figure out why you got that error. Could you please check if you download the pretrained mask-cnn model and PCPA dataset well? Or if you change any part of the program, please let me know the detail.

**Comment by Jennifercheukyin** [comment]
Hi Haolin, thank for getting back! 
1. Shouldn't the input size to RNN be 3d, batch size, time steps, and data dimension? 
2. I'm not exactly sure if I downloaded the pretrained mask-cnn model. I only downloaded the stuff mentioned in the readme file. 
Let me know if I missed anything, thank you thank you!

**Comment by OSU-Haolin** [comment]
> Hi Haolin, thank for getting back!
> 
> 1. Shouldn't the input size to RNN be 3d, batch size, time steps, and data dimension?
> 2. I'm not exactly sure if I downloaded the pretrained mask-cnn model. I only downloaded the stuff mentioned in the readme file.
>    Let me know if I missed anything, thank you thank you!

I think I find the problem. First, the batch size is 1 in default. The time step is 16 in our project. Your program may miss the CNN model. Because the data shown in the error message

**Comment by Jennifercheukyin** [comment]
> The correct data flow fed to RNN should be 16x512 (512 is the size of cnn features from every frame of RGB images). It seems that cnn features were not successfully generated. Please check the pretrained Vgg16 model and your JAAD dataset.
mask_cnn that comes after local_context_cnn generates a tensor of size (16,512). So is it this one that's gonna be fed into RNN? But in the get_model function under MASK_PCPA_4_2d (action_predict.py), line 5511 indicates that the tensor from local_context_cnn, which is of size (16,224,224,3), will be fed into a rnn. Could you clarify that? thanks!

**Comment by OSU-Haolin** [comment]
> > The correct data flow fed to RNN should be 16x512 (512 is the size of cnn features from every frame of RGB images). It seems that cnn features were not successfully generated. Please check the pretrained Vgg16 model and your JAAD dataset.
> 
> mask_cnn that comes after local_context_cnn generates a tensor of size (16,512). So is it this one that's gonna be fed into RNN? But in the get_model function under MASK_PCPA_4_2d (action_predict.py), line 5511 indicates that the tensor from local_context_cnn, which is of size (16,224,224,3), will be fed into a rnn. Could you clarify that? thanks!



I'll take MASK_PCPA_4_2d (line 5511) for example as you mentioned.

![image](https://user-images.githubusercontent.com/56414452/119254717-84d19080-bbea-11eb-9104-e53901e3d4dd.png)


**The data flow for context_cnn:** 

line 5457 use `get_context_data`  function  ( to get context_cnn features that should be fed to RNN)

line 773 shows the detail of `get_context_data`

line 818 see `load_images_crop_and_process`

line 248 shows the detail of `load_images_crop_and_process`

line 281-282 shows that we load the pre-trained VGG19 model

line 344 and 349 show that if the feature type is 'local_context_cnn', the CNN features will be generated by the VGG model from the images with the size of (16,224,224,3).

Finally, CNN image features with the size of (16,512) (I am not sure if it is exactly 512 because it's been so long not running this program) will be returned to our original function call `get_context_data` (line 5457), and fed to the RNN modules in the model of MASK_PCPA_4_2d.

**Comment by Jennifercheukyin** [comment]
Thank you for replying Haolin. 

> line 344 and 349 show that if the feature type is 'local_context_cnn', the CNN features will be generated by the VGG model from the images (224,224,3).
> 
> Finally, CNN image features with the size of (16,512) (I am not sure if it is exactly 512 because it's been so long not running this program) will be returned to our original function call get_context_data (line 5457), and fed to the RNN modules in the model of MASK_PCPA_4_2d.

Just to make sure I got you right, if `load_images_crop_and_process` functions correctly, when `crop_type='local_context_cnn'`, the final feature returned from `load_images_crop_and_process` will be of size (16,512)?

**Comment by OSU-Haolin** [comment]
> Thank you for replying Haolin.
> 
> > line 344 and 349 show that if the feature type is 'local_context_cnn', the CNN features will be generated by the VGG model from the images (224,224,3).
> > Finally, CNN image features with the size of (16,512) (I am not sure if it is exactly 512 because it's been so long not running this program) will be returned to our original function call get_context_data (line 5457), and fed to the RNN modules in the model of MASK_PCPA_4_2d.
> 
> Just to make sure I got you right, if `load_images_crop_and_process` functions correctly, when `crop_type='local_context_cnn'`, the final feature returned from `load_images_crop_and_process` will be of size (16,512)?

Yes! If there is no problem in functions of get_context_data as well as load_images_crop_and_process, vgg features will be generated. Please git clone the original code and try to run it following the readme instruction. The program had been tested successfully before we uploaded it here.

**Comment by dschoerk** [comment]
hi, i ran into the same error as mentioned by Jennifer. code is equal to your repo. since this seems to work at your end i assume we might be using different versions of tensorflow. what version are you using? could you provide a pip freeze or something similar listing your installed packages please?

**Comment by Jennifercheukyin** [comment]
> ~hi, i ran into the same error as mentioned by Jennifer. code is equal to your repo. since this seems to work at your end i assume we might be using different versions of tensorflow. what version are you using? could you provide a pip freeze or something similar listing your installed packages please?~
> 
> error should be fixed with PR #5
> i believe the wrong context data was generated. original code created 224x224x3 arrays in pkl files which looks like image crops instead of VGG features. seems like the string identifier to create local context cnn features was incorrect.
> 
> result of the MASK_PCPA_jaad_2d.yaml model
> ![grafik](https://user-images.githubusercontent.com/913265/120039554-6a8e1d00-c005-11eb-9354-c83e7d62cdec.png)

**Comment by Jennifercheukyin** [comment]
I actually did notice that the "crop_type" doesn't match with the one in load_image_crop_and_process. I just changed to 'local_contect_cnn' as indicated in your pr, but locally I'm still getting the error.

**Comment by dschoerk** [comment]
The program is caching the features to pkl files, you need to delete the folder data/features/jaad/local_context_cnn to recreate the correct features

**Comment by Jennifercheukyin** [comment]
Got it working, thank you so very much!
