### ISSUE TITLE
Pre-trained 

### ISSUE THREAD

**Issue by gv237-07** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#4]
Hi. Thank you for your amazing work. Could you please post a link for the pre-trained model please? Because the link at the bottom of the README seems to be broken. Thank you for your help

**Comment by OSU-Haolin** [comment]
Hi, thanks for your interest in our work! 

Later I will let you know when I update the BaiduDisk link and post the Google Drive link.

**Comment by OSU-Haolin** [comment]
Now pre-trained models were uploaded and you can see links in README.
It is better to try a larger dataset such as the PIE dataset for achieving more reliable results.

**Comment by gv237-07** [comment]
Thank you for your help
