### ISSUE TITLE
zip with models on google drive broken

### ISSUE THREAD

**Issue by dschoerk** [OSU-Haolin/Pedestrian_Crossing_Intention_Prediction#7]
thanks for uploading the models to google drive, unfortunately the file seems to be damaged

![grafik](https://user-images.githubusercontent.com/913265/120324540-0ad69100-c2e7-11eb-897c-8e2278768609.png)

tried to download it a couple of times, but it seems like the uploaded file has an issue

**Comment by OSU-Haolin** [comment]
Thanks for posting the issue here!
I will check that and find a solution later.

**Comment by dongfang-steven-yang** [comment]
@dschoerk hi, we have just updated the Google Drive for the pre-trained, it should be working now.
